// api paths, relative to NEXT_PUBLIC_API_URL. see /docs on the api for the contract
export const endpoints = {
  health: "/health",
  auth: {
    signup: "/v1/auth/signup",
    login: "/v1/auth/login",
    verifyOtp: "/v1/auth/verify-otp",
    demoToken: "/v1/auth/demo-token",
  },
  me: "/v1/me",
  demo: {
    loginAs: "/v1/demo/login-as",
  },
  bank: {
    login: "/v1/bank/login",
    verifyMfa: "/v1/bank/login/verify",
    demoLogin: "/v1/bank/demo-login",
    logout: "/v1/bank/logout",
    password: "/v1/bank/password",
    overview: "/v1/bank/overview",
    commitments: "/v1/bank/commitments",
    commitment: (id: string) => `/v1/bank/commitments/${encodeURIComponent(id)}`,
    commitmentGroupHealth: (id: string) => `/v1/bank/commitments/${encodeURIComponent(id)}/group-health`,
    commitmentCases: (id: string) => `/v1/bank/commitments/${encodeURIComponent(id)}/cases`,
    resolveCommitmentCase: (id: string, caseId: string) =>
      `/v1/bank/commitments/${encodeURIComponent(id)}/cases/${encodeURIComponent(caseId)}/resolve`,
    users: "/v1/bank/users",
    user: (id: string) => `/v1/bank/users/${encodeURIComponent(id)}`,
    userScore: (id: string) => `/v1/bank/users/${encodeURIComponent(id)}/score`,
    userCommitments: (id: string) => `/v1/bank/users/${encodeURIComponent(id)}/commitments`,
    userActivity: (id: string) => `/v1/bank/users/${encodeURIComponent(id)}/activity`,
    userFlags: (id: string) => `/v1/bank/users/${encodeURIComponent(id)}/flags`,
    userRestriction: (id: string) => `/v1/bank/users/${encodeURIComponent(id)}/restriction`,
    userRestrictions: (id: string) => `/v1/bank/users/${encodeURIComponent(id)}/restrictions`,
    userRevokeSessions: (id: string) => `/v1/bank/users/${encodeURIComponent(id)}/sessions/revoke`,
    auditLog: "/v1/bank/audit-log",
    auditLogExport: "/v1/bank/audit-log/export",
    flags: "/v1/bank/flags",
    flag: (id: string) => `/v1/bank/flags/${encodeURIComponent(id)}`,
    resolveFlag: (id: string) => `/v1/bank/flags/${encodeURIComponent(id)}/resolve`,
    runRiskRules: "/v1/bank/risk-rules/run",
    settlements: "/v1/bank/settlements",
    developers: "/v1/bank/developers",
    apiKeys: "/v1/bank/api-keys",
    apiKey: (id: string) => `/v1/bank/api-keys/${encodeURIComponent(id)}`,
    rotateApiKey: (id: string) => `/v1/bank/api-keys/${encodeURIComponent(id)}/rotate`,
    webhooks: "/v1/bank/webhooks",
    webhook: (id: string) => `/v1/bank/webhooks/${encodeURIComponent(id)}`,
    testWebhook: (id: string) => `/v1/bank/webhooks/${encodeURIComponent(id)}/test`,
    rotateWebhookSecret: (id: string) => `/v1/bank/webhooks/${encodeURIComponent(id)}/rotate-secret`,
    webhookDeliveries: (id: string) => `/v1/bank/webhooks/${encodeURIComponent(id)}/deliveries`,
    events: "/v1/bank/events",
    team: "/v1/bank/team",
    staff: (id: string) => `/v1/bank/team/${encodeURIComponent(id)}`,
    staffPasswordReset: (id: string) => `/v1/bank/team/${encodeURIComponent(id)}/password-reset`,
    staffPermissions: (id: string) => `/v1/bank/team/${encodeURIComponent(id)}/permissions`,
    settings: "/v1/bank/settings",
  },
} as const
