"""Migration wiring.

Two failures here are silent until they are expensive, so they get tests.

A second Alembic head makes `alembic upgrade head` refuse to run at all, and it
looks like a working tree until the moment anyone tries to deploy.

Bank tables live in `app/bank/models.py`, not `app/models.py`. If Alembic's
metadata does not include that module, the tables read as ones that should no
longer exist, and the next autogenerated migration drops them.
"""

import ast
from pathlib import Path

from alembic.config import Config
from alembic.script import ScriptDirectory

from app.bank.models import BankAuditEvent, BankPartner, BankStaff, RiskFlag
from app.database import Base


BACKEND_DIR = Path(__file__).resolve().parents[1]
ALEMBIC_INI = BACKEND_DIR / "alembic.ini"
ENV_PY = BACKEND_DIR / "alembic" / "env.py"


def _script_directory() -> ScriptDirectory:
    return ScriptDirectory.from_config(Config(str(ALEMBIC_INI)))


def test_there_is_exactly_one_migration_head():
    """`alembic upgrade head` cannot resolve two.

    Two revisions both descending from the same parent is easy to produce when
    two branches are developed at once, and nothing complains until a deploy.
    """
    heads = _script_directory().get_heads()
    assert len(heads) == 1, f"expected a single head, found {heads}"


def test_the_new_bank_staff_revision_is_in_the_chain():
    heads = _script_directory().get_heads()
    assert heads == ["0010_bank_staff_login"]


def test_bank_tables_are_present_in_the_orm_metadata():
    for table in (BankPartner, RiskFlag, BankAuditEvent, BankStaff):
        assert table.__tablename__ in Base.metadata.tables


def test_alembic_metadata_includes_the_bank_models_module():
    """Guards the import in `alembic/env.py` itself.

    Checking `Base.metadata` directly is not enough, because the test process
    imports the bank models itself. What matters is the import Alembic performs,
    so this reads the file rather than re-creating its behaviour.
    """
    tree = ast.parse(ENV_PY.read_text(encoding="utf-8"))
    imported = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module)

    assert "app.bank.models" in imported or "app.bank" in imported, (
        "alembic/env.py does not import the bank models, so autogenerate will "
        "propose dropping bank_partners, risk_flags, bank_audit_events and bank_staff"
    )
