"""Migration wiring.

Two failures here are silent until they are expensive, so they get tests.

A second Alembic head makes `alembic upgrade head` refuse to run at all, and it
looks like a working tree until the moment anyone tries to deploy.

Bank tables live in `app/bank/models.py`, not `app/models.py`. If Alembic's
metadata does not include that module, the tables read as ones that should no
longer exist, and the next autogenerated migration drops them.
"""

import ast
from pathlib import Path

from alembic.config import Config
from alembic.script import ScriptDirectory

from app.bank.models import AccountRestriction, BankApiKey, BankAuditEvent, BankPartner, BankStaff, RiskFlag, WebhookDelivery, WebhookSubscription
from app.database import Base
from app.models import LinkedAccount, PlatformAuditEvent, SessionRevocation, TrustedDevice

BACKEND_DIR = Path(__file__).resolve().parents[1]
ALEMBIC_INI = BACKEND_DIR / "alembic.ini"
ENV_PY = BACKEND_DIR / "alembic" / "env.py"
RELEASE_READINESS = BACKEND_DIR / "demo docs" / "RELEASE_READINESS.md"


def _script_directory() -> ScriptDirectory:
    config = Config(str(ALEMBIC_INI))
    # CI runs from backend, while local checks often run from the repository
    # root. Resolve this explicitly so both validate the same revision graph.
    config.set_main_option("script_location", str(BACKEND_DIR / "alembic"))
    return ScriptDirectory.from_config(config)


def test_there_is_exactly_one_migration_head():
    """`alembic upgrade head` cannot resolve two.

    Two revisions both descending from the same parent is easy to produce when
    two branches are developed at once, and nothing complains until a deploy.
    """
    heads = _script_directory().get_heads()
    assert len(heads) == 1, f"expected a single head, found {heads}"


def test_bank_migration_paths_merge_at_the_expected_head():
    heads = _script_directory().get_heads()
    assert heads == ["0019_member_auth"]


def test_release_readiness_documents_the_current_migration_head():
    """The deployment runbook must not direct a release to an old revision."""
    head = _script_directory().get_heads()[0]
    assert head in RELEASE_READINESS.read_text(encoding="utf-8")


def test_migration_identifiers_fit_the_existing_version_column():
    """Render's established Alembic table uses the standard VARCHAR(32)."""
    revisions = list(_script_directory().walk_revisions())
    too_long = [revision.revision for revision in revisions if len(revision.revision) > 32]
    assert not too_long, f"Alembic revision IDs exceed VARCHAR(32): {too_long}"


def test_bank_tables_are_present_in_the_orm_metadata():
    for table in (
        BankPartner,
        RiskFlag,
        AccountRestriction,
        BankAuditEvent,
        BankStaff,
        BankApiKey,
        WebhookSubscription,
        WebhookDelivery,
        SessionRevocation,
        PlatformAuditEvent,
        LinkedAccount,
        TrustedDevice,
    ):
        assert table.__tablename__ in Base.metadata.tables


def test_certification_schema_matches_the_models():
    """The 0014 migration and the ORM have to agree, or deploy and dev diverge.

    A column added to a model without a migration reads fine in tests, because
    tests build their schema from the ORM, and then fails against the deployed
    database. The comparison is by name and type rather than by running the
    migration, so a missing column is caught without a database.
    """
    script = _script_directory()
    revision = script.get_revision("0014_certification_schema")
    assert revision is not None

    # Every column the certification models declare must exist in the migration
    # text. Reading the file keeps this honest even when the migration only runs
    # against a live PostgreSQL instance we do not have here.
    source = Path(revision.path).read_text(encoding="utf-8")
    expected = [
        "session_revocations",
        "platform_audit_events",
        "account_restrictions",
        "account_status",
        "session_invalidated_at",
    ]
    missing = [name for name in expected if name not in source]
    assert not missing, f"0014 migration is missing: {missing}"


def test_certification_migration_actually_runs_against_the_previous_schema():
    """Run 0014 for real, on a database shaped like the one 0013 left behind.

    Reading the file for names catches a missing column; it does not catch a
    migration that raises. This executes ``upgrade`` against a minimal pre-0014
    ``users`` table and then asserts the resulting schema through SQLAlchemy's
    inspector, which is the same check a deploy would hit.

    Full ``alembic upgrade head`` cannot be used here: revision 0002 fails on
    SQLite with ``near "ALTER": syntax error`` because it emits ALTER COLUMN,
    which SQLite does not support. That is a separate, pre-existing problem, so
    this exercises the new revision in isolation.
    """
    import sqlalchemy as sa
    from alembic.migration import MigrationContext
    from alembic.operations import Operations

    engine = sa.create_engine("sqlite+pysqlite://")
    with engine.begin() as connection:
        # The subset of the 0013 schema that 0014 alters.
        connection.execute(
            sa.text("CREATE TABLE users (id VARCHAR PRIMARY KEY, name VARCHAR NOT NULL, phone VARCHAR NOT NULL)")
        )
        connection.execute(sa.text("CREATE TABLE bank_partners (id VARCHAR PRIMARY KEY)"))
        connection.execute(sa.text("CREATE TABLE risk_flags (id VARCHAR PRIMARY KEY)"))

        revision = _script_directory().get_revision("0014_certification_schema")
        module = revision.module
        with Operations.context(MigrationContext.configure(connection)):
            module.upgrade()

        inspector = sa.inspect(connection)
        user_columns = {column["name"] for column in inspector.get_columns("users")}
        assert {
            "account_status",
            "restriction_reason",
            "restricted_by",
            "restricted_at",
            "session_invalidated_at",
        } <= user_columns, f"0014 did not add every user column: {user_columns}"

        assert "session_revocations" in inspector.get_table_names()
        assert "platform_audit_events" in inspector.get_table_names()
        assert "account_restrictions" in inspector.get_table_names()

        # Existing rows must come out of the migration usable, not with a null
        # status the authorisation path would then read as "not active".
        connection.execute(sa.text("INSERT INTO users (id, name, phone) VALUES ('u1', 'Old', '+1')"))
        backfilled = connection.execute(sa.text("SELECT account_status FROM users WHERE id = 'u1'")).scalar()
        assert backfilled == "active", "existing rows were not defaulted to active"

        # And it has to come back down cleanly.
        with Operations.context(MigrationContext.configure(connection)):
            module.downgrade()

        inspector = sa.inspect(connection)
        assert "platform_audit_events" not in inspector.get_table_names()
        assert "session_revocations" not in inspector.get_table_names()
        assert "account_restrictions" not in inspector.get_table_names()
        assert "account_status" not in {column["name"] for column in inspector.get_columns("users")}

    engine.dispose()


def test_alembic_metadata_includes_the_bank_models_module():
    """Guards the import in `alembic/env.py` itself.

    Checking `Base.metadata` directly is not enough, because the test process
    imports the bank models itself. What matters is the import Alembic performs,
    so this reads the file rather than re-creating its behaviour.
    """
    tree = ast.parse(ENV_PY.read_text(encoding="utf-8"))
    imported = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module)

    assert "app.bank.models" in imported or "app.bank" in imported, (
        "alembic/env.py does not import the bank models, so autogenerate will "
        "propose dropping bank_partners, risk_flags, bank_audit_events and bank_staff"
    )
